doc-warnings: yes
max-line-length: 160
uses:
  - django
  - celery
ignore-paths:
  - docs
  - hooks
  - price_monitor/migrations
pylint:
  disable:
    - invalid-encoded-data
    - model-missing-unicode
python-targets:
  - 3